# Generated by Django 5.0.3 on 2024-06-25 17:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(default='Dumka', max_length=100)),
                ('City', models.CharField(default='Dumka', max_length=100)),
                ('State', models.CharField(default='Jharkhand', max_length=100)),
                ('Country', models.CharField(default='India', max_length=100)),
                ('ZipCode', models.CharField(default='814101', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(default='Dumka', max_length=100)),
                ('City', models.CharField(default='Dumka', max_length=100)),
                ('State', models.CharField(default='Jharkhand', max_length=100)),
                ('Country', models.CharField(default='India', max_length=100)),
                ('ZipCode', models.CharField(default='814101', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=14)),
                ('PANNumber', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
                ('Remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('Id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('StartDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='databases.address')),
                ('Email', models.EmailField(max_length=255)),
                ('Phone', models.CharField(max_length=14)),
            ],
            bases=('databases.address',),
        ),
        migrations.CreateModel(
            name='StoreGroup',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(default='Dumka', max_length=100)),
                ('City', models.CharField(default='Dumka', max_length=100)),
                ('State', models.CharField(default='Jharkhand', max_length=100)),
                ('Country', models.CharField(default='India', max_length=100)),
                ('ZipCode', models.CharField(default='814101', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=14)),
                ('PANNumber', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
                ('Remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('Id', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.client')),
            ],
            options={
                'verbose_name': 'StoreGroup',
                'verbose_name_plural': 'StoreGroups',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Address', models.CharField(default='Dumka', max_length=100)),
                ('City', models.CharField(default='Dumka', max_length=100)),
                ('State', models.CharField(default='Jharkhand', max_length=100)),
                ('Country', models.CharField(default='India', max_length=100)),
                ('ZipCode', models.CharField(default='814101', max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=14)),
                ('PANNumber', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('Active', models.BooleanField(default=True)),
                ('Remarks', models.CharField(blank=True, max_length=200, null=True)),
                ('ContactPerson', models.CharField(blank=True, max_length=100, null=True)),
                ('Id', models.CharField(db_index=True, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('StoreCode', models.CharField(max_length=15, unique=True)),
                ('BeginDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('EndDate', models.DateTimeField(blank=True, null=True)),
                ('StoreManager', models.CharField(max_length=100)),
                ('StoreManegerContactNo', models.CharField(max_length=100)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.client')),
                ('StoreGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databases.storegroup')),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
